fixed undefined array issue
jaredwray/keyv pull request #432
Opened 2022-08-15 15:45 UTC by alphmth

Fixes #431

2022-08-15 16:06 UTC, jaredwray requested changes

2022-08-15 16:06 UTC, jaredwray commented on packages/etcd/package.json
> +		"etcd3": "1.1.0",
@alphmth - can you please move this back to `^1.1.0`

2022-08-15 16:06 UTC, jaredwray commented on packages/memcache/package.json
> +		"test": "nyc ava",
please move this back to `xo && nyc ava`

2022-08-15 17:06 UTC, jaredwray approved these changes

2022-08-15 17:07 UTC, merged

2022-08-18 20:48 UTC, trevor-scheer commented
Thanks for taking care of this @alphmth!